//! Demo: print the OpenAPI 3.1 document generated for a small zchema API.

const std = @import("std");
const zchema = @import("zchema");

const User = struct {
    id: u32,
    name: []const u8,

    pub const jsonschema = .{ .name = "User", .description = "A user record." };
};

const CreateUser = struct {
    name: []const u8,

    pub const jsonschema = .{
        .name = "CreateUser",
        .fields = .{ .name = .{ .minLength = 1, .maxLength = 128 } },
    };
};

const Problem = struct {
    message: []const u8,

    pub const jsonschema = .{ .name = "Problem" };
};

fn createUser(body: zchema.Body(CreateUser)) !zchema.Created(User) {
    return .{ .value = .{ .id = 1, .name = body.value.name } };
}

fn listUsers() ![]const User {
    return &.{};
}

fn getUser(req: *std.http.Server.Request, arena: std.mem.Allocator) !void {
    _ = req;
    _ = arena;
}

const GetUserResponse = zchema.Response(.{
    zchema.case(.ok, User),
    zchema.case(.not_found, Problem),
});

const Api = zchema.Api(.{
    zchema.post("/users", createUser),
    zchema.get("/users", listUsers),
    zchema.op(.GET, "/users/{id}", getUser, .{
        .request = zchema.Request(.{ .path = struct { id: u32 } }),
        .response = GetUserResponse,
    }),
});

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();

    const doc = try zchema.openApiJson(Api, arena, .{
        .title = "Users API",
        .version = "1.0.0",
        .description = "Demo API generated by zchema.",
    });

    var stdout_buffer: [4096]u8 = undefined;
    var stdout_file_writer: std.Io.File.Writer = .init(.stdout(), init.io, &stdout_buffer);
    const stdout = &stdout_file_writer.interface;
    try stdout.writeAll(doc);
    try stdout.writeByte('\n');
    try stdout.flush();
}

test "demo API generates a valid OpenAPI document" {
    const doc = try zchema.openApiJson(Api, std.testing.allocator, .{ .title = "Users API" });
    defer std.testing.allocator.free(doc);

    const parsed = try std.json.parseFromSlice(std.json.Value, std.testing.allocator, doc, .{});
    defer parsed.deinit();
    try std.testing.expect(std.mem.indexOf(u8, doc, "\"openapi\":\"3.1.1\"") != null);
}
